### ISSUE TITLE
Does not work overlay in Safari

### ISSUE THREAD

**Issue by beautyfree** [gilbarbara/react-joyride#126]
As we found out, the method for determining the browser does not work for safari and [this line](https://github.com/gilbarbara/react-joyride/blob/7c7027e2e8c0d0d2b30ad88947b1812a0b53df7c/src/scripts/utils.js#L35) return false as well as other conditions

If I add a class `safari` manually it fixes the problem

Safari 10.0.1 
and also on the iphone Safari

![yt7zae4zayk jpg 1440x900](https://cloud.githubusercontent.com/assets/656531/19072101/1199edae-8a3c-11e6-8bea-2e3f6ea59c23.png)

**Comment by codyrushing** [comment]
I'm experiencing the same issue

**Comment by Firfi** [comment]
Same issue here.

**Comment by Firfi** [comment]
Also related to latest comments to most upvoted answer here: http://stackoverflow.com/questions/9847580/how-to-detect-safari-chrome-ie-firefox-and-opera-browser

Safari detection proposed there and used in this lib also doesn't work anymore.

**Comment by lcvbeek** [comment]
http://stackoverflow.com/questions/39120772/how-to-detect-safari-10-browser-in-javascript/39621764#39621764 says to update the line to this in order to detect Safari 10.

`var isSafari=Object.prototype.toString.call(window.HTMLElement).indexOf('Constructor')>0||!isChrome && !isOpera&&window.webkitAudioContext!==undefined;`

I haven't tested it yet but wanted to share. Will update when I get the chance to test.

**Comment by gustavs-gutmanis** [comment]
@lcvbeek - I just tried it, it works!

**Comment by lcvbeek** [comment]
@gustavs-gutmanis Haha no I just found someone else's fix. You actually tested it and applied it correctly, honor's all yours. :)

**Comment by gustavs-gutmanis** [comment]
Alright, buddy. I'll see what I can do.

**Comment by gilbarbara** [comment]
Hey, sorry for the delay.
Fixed in 3985491314ddd948a7b2a133a684725af476055e (1.5.1)

**Comment by gilbarbara** [comment]
Oops, test is broken. I'll fix it tomorrow.

**Comment by gilbarbara** [comment]
Alright, all fixed.
Published as 1.5.1
