### ISSUE TITLE
step:before event on continuous type

### ISSUE THREAD

**Issue by Joey92** [gilbarbara/react-joyride#128]
Currently the callback with `step:before` is only called when you click on the beacon.
I have a continuous joyride and need a pre-step as well.

Currently there is 1 `step:before` event emitted on a continuous joyride and only `step:after` events for each step after.

The current event `step:before` should be named to `beacon:click` or so. `step:before` should be emitted even for continuous on each step, since it represents some kind of pre-opening of a step.

These would be breaking changes though for each implementation using it how it currently is.

What do you think?

**Comment by vning93** [comment]
+1

**Comment by adrian-c-petrescu** [comment]
I am on the same page with @Joey92 . If you need to prepare the UI for being presented in the next step (e.g. opening a menu, showing the hovered state of a control), you need to do it in the "before" callback for that step. 

Faking this feature with the "step:after" of the previous step works only halfway, because navigating backward will not work as expected.

**Comment by gilbarbara** [comment]
Fixed in 3888cdeb479c398907c24887563cc6708c29f405
