### ISSUE TITLE
[Feature request] callback on spotlight click

### ISSUE THREAD

**Issue by CrackersAreNotCookies** [gilbarbara/react-joyride#385]
>Expected behavior
As a developer, I want to be able to perform some actions (for example advance the tour) whenever the user click something inside the spotlight. I would like to be able to edit the tour behaviour without looking in other files.

>Actual behavior
Actually there's no such callback / listener to detect spotlight click, and I have to put my callbacks inside other components for example onClick functions. So when I have to modify a step, I often need to edit other files that, in my opinion, shouldn't have code regarding the tour.

>React version
16.4.0

>React-Joyride version
2.0.0-10

**Comment by gilbarbara** [comment]
Did you check the `Controlled` example in the demo?
It has a click-through behavior that can suit your need.

**Comment by MilllerTime** [comment]
@CrackersAreNotCookies I was thinking this might be nice too, but I changed my mind as I thought about it more. I can't think of a situation where it doesn't damage the user experience.

The tour pop ups provide buttons for navigating the tour. All other buttons in an app are not meant to control the tour, they're meant for the app itself. As you said, you don't think the button's code should have to know about the tour. By the same logic, why should the button advance the tour at all? Is that what a user expects to happen? I can't imagine that being the case -- there are dedicated controls for that.

If you want the button to both do its normal thing **and** advance the tour, all in one click event, it doesn't matter where you attach that event, you're going to be coupling the button action and tour logic.

The final nail in the coffin is that if you allow the spotlight element to receive clicks, the button itself has to be covered up. This means `:hover` and `:active` states won't work, which breaks styling consistency in your app and poses an accessibility problem.

I don't think there are any ways around these issues, and so I don't think it's a very useful feature.

If you disagree, perhaps more detail about your use case would help.

**Comment by CrackersAreNotCookies** [comment]
@gilbarbara yes, I took most of my code out of the demo controlled example, there isn't such a callback

@MilllerTime I see your point, so before answering I need to share some infos about the application I'm using the tutorial in: The application on login receive data from the user and save it in redux store, this including the tutorial progress. To do so, my steps array is a json with a bunch of objects, each one corresponding to a tutorial 'phase' (so a group of steps that need to be performed in order to save the progress on the backend), so this object will be something like this:
`{
    phase1: {
        name: 'phase1',
        next: 'phase2',
        steps: [/* array of steps objects */]
    },
    phase2: { ... }
}`

On login I check if the user's current phase is the last one, if yes, the tutorial is complete and the Joyride component won't get mounted at all. Because of this I would like that all the logic regarding the tutorial, would stay in its own component.

You're true when you say that I will still mix the button logic with the tour logic implementing this, however, when the tour component is not mounted the button will not know about the tour logic at all.

On the implementation side, I must be honest I have no clue how the spotlight is generated, So I understand if detecting the spotlight click is something not doable without breaking the normal application workflow.

It's true that we have buttons to advance and revert the tour, however I still believe it's more intuitive for the user to interact directly with the application.

**Comment by MilllerTime** [comment]
> On the implementation side, I must be honest I have no clue how the spotlight is generated, So I understand if detecting the spotlight click is something not doable without breaking the normal application workflow.

This is the biggest issue IMO. Joyride mounts its DOM nodes outside of your main application tree, meaning that Joyride DOM nodes and your app DOM nodes are in sibling trees. This means bubbling events, including mouse/touch events, will not propagate from your app nodes up through the Joyride nodes. The spotlight is a Joyride DOM node, and if you want to put a click event on it, then it will intercept **all** mouse and touch events and prevent them from going to your app. You can prevent this and allow mouse/touch events to pass through the spotlight using the official `spotlightClicks` prop (I assume it uses the CSS `pointer-events` property), but then you can't detect clicks on the spotlight at all. You get one or the other, not both. If you detect clicks on the spotlight, your button won't react to hover and other pointer-based interactions anymore.

> You're true when you say that I will still mix the button logic with the tour logic implementing this, however, when the tour component is not mounted the button will not know about the tour logic at all.

It sounds like you'd prefer to shift this complexity into the tour itself, rather than the button or other components. I can understand the desire to avoid complicating the app because of the tour, but it's still coupling things you wouldn't normally couple.

> It's true that we have buttons to advance and revert the tour, however I still believe it's more intuitive for the user to interact directly with the application.

If the user is performing app-specific actions, sure. But if the user is clicking an in-app button that normally does something other than advance the tour, it seems odd that it would advance the tour instead.

If you're using Redux and have a transactional system for controlling your app, it's probably not _too_ far fetched to imagine a solution where some action can check if the tour is running, and if so advance the tour to the next step in addition to whatever it normally does. You can even abstract this behavior into a helper. I am currently doing this in a couple places in an app. I track the current tour and step in redux and have actions/selectors for controlling and reading tour state at a higher level than Joyride. It's not _too_ bad orchestrating it all, and I think is a better solution than using raw click events to trigger the non-standard flows.

**Comment by gilbarbara** [comment]
> You get one or the other, not both. If you detect clicks on the spotlight, your button won't react to hover and other pointer-based interactions anymore.

This pretty much explain how it works. If you can think in a better way, feel free to submit a PR.

**Comment by nthgol** [comment]
+1 on this issue though I don't understand it fully. 
At the moment it seems I need to infiltrate my spotlight components with some kind of a callback to modify the tour. Spotlight clicks should easily be able to advance the tour.

**Comment by loukmane-issa** [comment]
I saw this marked as completed. I really wanted this as I wanted to decouple my Tours code from my react components, so that the components will focus only on their own logic and will not have to contain logic for the tour.

I was able to achieve this with the following code:

```
const handleSpotlightClick = (event: MouseEvent) => {
    const currentStep = steps[stepIndex];
    const isLastStep = stepIndex === steps.length - 1;
    if (
      currentStep.spotlightClicks
    ) {
      let target = event.target as HTMLElement;
      // This is possible because I just use class selector, but you can easily change this
      while (target && !target.classList.contains(currentStep.target)) {
        target = target.parentElement as HTMLElement;
      }
      if (target.classList.contains(currentStep.targetClass)) {
        if (isLastStep) {
          onComplete?.();
        } else {
          setStepIndex(stepIndex + 1);
        }
      }
    }
  };
```

```

  useEffect(() => {
    document.addEventListener('click', handleSpotlightClick);
    return () => {
      document.removeEventListener('click', handleSpotlightClick);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
    // This is required, so that the handleClick always get the latest stepIndex
  }, [stepIndex]);
```

Not sure if there's a better way to do this though. I couldn't find it anywhere.
