### ISSUE TITLE
Improperly sized close button

### ISSUE THREAD

**Issue by LtAstros** [gilbarbara/react-joyride#401]
>Expected behavior
![screen shot 2018-07-16 at 1 19 48 pm](https://user-images.githubusercontent.com/25091888/42782754-af6a534e-88fe-11e8-899c-2d4cdb9f47ea.png)

>Actual behavior
![screen shot 2018-07-16 at 1 18 45 pm](https://user-images.githubusercontent.com/25091888/42782775-b67511ec-88fe-11e8-8e03-25bdb5d28458.png)

>Steps to reproduce the problem
When I originally imported react-joyride the close button looked like the one in the actual behavior section. So I notices that there were height and width properties got the 'svg' for the close button but not wrapped in a 'style' tag. Could this have been an error on my part or a bug? (Sorry for the undetailed explanation, its my first issue I ever filed on GitHub and I don't know proper lingo :)

>React version
15.6.2

>React-Joyride version
2.0.0-11

**Comment by gilbarbara** [comment]
hey,
I would need a working demo to debug what happened. You could be resetting the SVG styles somehow...

**Comment by gilbarbara** [comment]
So it's a problem with your own setup, not the library?
Sorry, I can't help with implementation.

**Comment by LtAstros** [comment]
Just to clarify a little more, when npm installing, it creates lib folder where it seems that I am getting the React-Joyride stuff. when I edit the main src file (lets say, to hardcode some css) it doesn't effect the styles of the step bubbles, but if I hardcode in the lib file it does change the style. So if I check the properties of the svg it looks like this:
```
React.createElement(
      'svg',
      {
        width: width + 'px',
        height: height + 'px',
        viewBox: '0 0 18 18',
        version: '1.1',
        xmlns: 'http://www.w3.org/2000/svg',
        preserveAspectRatio: 'xMidYMid'
      },
```
This created made this svg 140x140 but when I added:
```
React.createElement(
      'svg',
      {
        style: {
          width: width + 'px',
          height: height + 'px',
        },
        viewBox: '0 0 18 18',
        version: '1.1',
        xmlns: 'http://www.w3.org/2000/svg',
        preserveAspectRatio: 'xMidYMid'
      },
```
It actually began to track the height and width styles.
Is that still a problem with implementation?

**Comment by gilbarbara** [comment]
You definitely shouldn't be editing the package code since it will get overridden when you update the dependencies. 🙏🏻

You are setting a global css rule to change the dimensions of ALL SVGs on the page in https://github.com/ageofmakers/ageofmakers-chrome/blob/onboarding-tutorial/app/src/sass/_profile.scss#L45
You should restrict that change to the specific element that needs that size and transforms.

Anyway, width and height are valid SVG attributes and they are used to set the element dimensions. However the cascading part of CSS means the style on the element will always beat the global style for it that in turn will always override the element attributes...

Always inspect the code with dev tools to make sure where the element styles are coming from!

[s]
