### ISSUE TITLE
Fix ARIA implementation

### ISSUE THREAD

**Issue by gilbarbara** [gilbarbara/react-joyride#460]
- [ ] Add focus to Beacon and Toolip when they are rendered
- [ ] Get text content from `title`, `locale` and possible others when they are React components to use as label

**Comment by catamphetamine** [comment]
And don't forget the `aria-live` attribute.

**Comment by gilbarbara** [comment]
@catamphetamine Everything I've read about ARIA and tooltips recommends using `aria-role="tooltip"`. Can you point me to a reliable source explaining why is it better to use `aria-region` with `aria-live` instead?

**Comment by catamphetamine** [comment]
@gilbarbara 
Well, I haven't seen a reliable source stating that `aria-role="tooltip"` can be used with `aria-live`.

**Comment by catamphetamine** [comment]
I can see you're using `aria-haspopup="dialog"`.
This is WAI-ARIA 1.1 feature and version 1.1 seems to be not implemented on most devices.
For better compatibility it's usually adviced to use v1.0.
https://www.w3.org/TR/wai-aria-1.0/states_and_properties#aria-haspopup
In version 1.0 `aria-haspopup` can only be `true/false`.
Version 1.0 clients will mistakenly assume that your button has a popup menu which may confuse the users.

> Indicates that the element has a popup context menu or sub-level menu.

-------

Choosing `alertdialog` role seems the correct choice.

Have you tested the build using VoiceOver or NVDA?

**Comment by gilbarbara** [comment]
Yeah, I've read a lot about ARIA these past days and differences between 1.0 and 1.1 specs including `haspopup` and this line changed my mind:
> The aria-haspopup property is an enumerated type. User agents MUST treat any value of aria-haspopup that is not included in the list of allowed values, including an empty string, as if the value false had been provided. To provide backward compatibility with ARIA 1.0 content, user agents MUST treat an aria-haspopup value of true as equivalent to a value of menu.
https://www.w3.org/TR/wai-aria-1.1/#aria-haspopup

However VoiceOver itself still treated the Beacon as a menu. I'll remove it and change the default `open` locale from the current **Open** string to **Open a dialog**. 0e46c9bc35e1263fbb7871ac5fb44be8148f3793

I've tested with VoiceOver with MacOS X 10.14.2. Can you test it with NVDA?

Anyway, I've published these changes with npm with the tag `next` and I've created this deployment so It can be live tested: https://react-joyride-pk3ugdo8d.now.sh

**Comment by catamphetamine** [comment]
> Yeah, I've read a lot about ARIA these past days

Same.
Our company decided to convert the website to an ARIA-compliant one.

> Can you test it with NVDA?
> https://react-joyride-pk3ugdo8d.now.sh

I opened the demo and it doesn't work in a sense that it doesn't read the tooltip conents.

"Clickable Next button Next"
"Clickable Next button Next"
"Clickable Next button Next"
"Clickable Last button Last"

A user can still read the tooltip contents by pressing the "Up" arrow key but in such case it will be reading backwards which is counter-intuitive.
It would read the tooltip if you focused the tooltip rather than a button.
At the same time, `alertdialog` advices focusing the button rather than the content.
https://www.w3.org/TR/wai-aria-1.0/roles#alertdialog

**Comment by catamphetamine** [comment]
> VoiceOver does read the content...

Then maybe it's NVDA behaving not correctly.

> I'll try to read more about it, change aria-live to assertive, etc.

You could try adding `aria-live`, yeah.
https://developer.mozilla.org/ru/docs/Web/Accessibility/ARIA/ARIA_Live_Regions

> To maximize compatibility, some people recommend adding a redundant aria-live="assertive" when using this role. However, adding both aria-live and role=alert causes double speaking issues in VoiceOver on iOS.

So VoiceOver will double-speak in that case.
I didn't test VoiceOver with `role="region"` because I'm not on a Mac.
Maybe it won't double speak there.
But conceptually `alertdialog` is a better choice than just a `region`.
So seems that there's no perfect solution at this point.

**Comment by gilbarbara** [comment]
The `aria-live` parameter is already on the main dialog div.
I can't use the role `region` for a popup that takes the focus out of the main website. It needs to be `dialog` or one of the sub-roles n(alert, alertdialog).

**Comment by gilbarbara** [comment]
I have published this in 2.0.2
It's not perfect, but ARIA implementation in different screen readers is confusing.
Thanks @catamphetamine and if you something to improve it, let me know!
