### ISSUE TITLE
react joyride - I am using react joyride some times it freeze the whole screen. Getting this waring in console "react-joyride: step has a custom scroll parent and can cause trouble with scrolling."

### ISSUE THREAD

**Issue by rohitGL** [gilbarbara/react-joyride#537]
## Link to repl or repo (highly encouraged)

Please provide a https://codesandbox.io/ demo or similar.

Issues without a reproduction link are likely to stall.

## Run `npx envinfo --system --binaries --npmPackages react-floater`

Paste the results here:

```bash

```

**Comment by gilbarbara** [comment]
It's impossible to know what is going on without seeing your setup running...

The console warning exists to let you know that your CSS is incorrect and the library tried to correct these issues. The first step to debug it is to fix these problems with overflow.
Try to fix that and/or remove this package to make sure the problem is caused by it.

If you confirm this, create a new issue filling all the required questions and with a link for a reproduction site.

I'm quite sure this package by itself wouldn't freeze the computer screen.
