### ISSUE TITLE
TypeError: Cannot read property 'removeEventListener' of undefined

### ISSUE THREAD

**Issue by linonetwo** [gilbarbara/react-joyride#542]
## 🐛 Bug Report

I put joyride on a list item, but when I remove that list item, following error occurs:

```
×
←→1 of 3 errors on the page
TypeError: Cannot read property 'removeEventListener' of undefined
JoyrideOverlay.componentWillUnmount
node_modules/react-joyride/es/index.js:1761
  1758 |     window.removeEventListener('resize', this.handleResize);
  1759 |     clearTimeout(this.resizeTimeout);
  1760 |     clearTimeout(this.scrollTimeout);
> 1761 |     this.scrollParent.removeEventListener('scroll', this.handleScroll);
       | ^  1762 |   }
  1763 | }, {
  1764 |   key: "updateState",
```

Possible here:

https://github.com/gilbarbara/react-joyride/blob/782fb7340f797d577dac59cac46f818a777808de/src/components/Overlay.js#L98

and 

https://github.com/gilbarbara/react-joyride/blob/324ab0d63bce7ba0abc1b68d9ad4de66393b811a/src/modules/dom.js#L120

## To Reproduce

...

## Expected behavior

Check if `this.scrollParent` is undefined.

## Link to repl or repo (highly encouraged)

I'm trying to create one but failed.

## Run `npx envinfo --system --binaries --npmPackages react-floater`

Paste the results here:

```bash
  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 57.56 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
```

**Comment by linonetwo** [comment]
Move it to be inside the component that will be remount, is a working workaround.

**Comment by gilbarbara** [comment]
I need a reproducing example in codesandbox or similar

**Comment by linonetwo** [comment]
Ouch, I tried, but I can't reproduce it online, too many codes might be related...

As long as it is fixed for my case, closing this.

**Comment by lukas1994** [comment]
Having the same issue. Did anyone figure out why this is happening? Tried wrapping the component in an error boundary but that also didn't help.

**Comment by linonetwo** [comment]
@lukas1994 can you reproduce it using stackblitz?

**Comment by lukas1994** [comment]
I can try that later this week. This is a stack trace if that helps.
![image](https://user-images.githubusercontent.com/6901762/78698199-df7e2f00-78f9-11ea-90d2-2e1bb64e1491.png)

**Comment by gndelia** [comment]
Hi, I'm having the same issue here. In my particular case, it only seems to be happening when running in production (minified code) as I cannot reproduce it in my local environment

**Comment by lukas1994** [comment]
same here, couldn't repro locally

**Comment by gilbarbara** [comment]
I definitely need an example here.

**Comment by gndelia** [comment]
in my case, I was able to fix it in our code. Though the example seems complex, because we use plenty of libraries (such as CRA, typescript, react-router, etc),  I will try to explain the scenario to see if it gives an idea. The repo is private, unfortunately, otherwise, I would have shared the code

I was only able to reproduce it in production env. Locally, it worked fine

### The scenario

There are two routes, `/index` and `/index/:id/view`. Each route is a different component, say `Home` and `View`

Both routes have the same heading style, with a title. It's a custom Header component, which is basically a styled `header`

We placed the  `data-beaconid` in this component.

Both `Home` and `View` components were under a `Switch` from `react-router`, so only one would be rendered at the same time.
The user would enter the page the first time in `Home`. Then, through a link, they would navigate to `View` in the FE side

In that process of navigation, the error would arise.

### The fix

What I noticed was that there were two instances of headers (one rendered in the `Home` and the other one in `View`.
So when navigating from `Home` to `View`, the `header` from the `Home` would be unmounted, and the `Header` from the `View` would be mounted. For the user was barely noticeable - the user always sees the header, while the content below changes.

The first ¿mistake? was that the header from `View` was missing the `data-beaconid` attribute, though our intention was to keep the beacon visible (as the header, for the user, was the same)

Though my first idea was just to add the attribute and see how it'd behave, I ended up doing something more reasonable: 
Given the header was literally the same, I lifted up to the component that was rendering both routes (the common parent) and rendered from there.

Now there was only one instance of the header. So far it seems it's working fine.

Hope it provides some guidance

**Comment by gilbarbara** [comment]
As @gndelia pointed out, the problem seems to be that unmounting a target while this library is working with it, will trigger this error.

The correct approach would be:

- advance to the next step BEFORE unmounting the target
- lift the target up in the tree to avoid unmounting
