### ISSUE TITLE
The spotlight or highlight doesn't resize if the child is resized by typing

### ISSUE THREAD

**Issue by crow1796** [gilbarbara/react-joyride#558]
## 🐛 Bug Report

The spotlight or highlight doesn't resize if the child is resized by typing.

## To Reproduce

1. Add a step that targets an element with an attribute of `contenteditable`
2. Run the tour
3. When you get to that element, type anything until the element's size overlaps the size of the spotlight **(WITHOUT MOVING YOUR MOUSE CURSOR)**

## Expected behavior

It would be great if the spotlight also gets resized when the child is resized.

## Link to repl or repo (highly encouraged)

https://codesandbox.io/s/cool-wildflower-lkiym?fontsize=14

**Comment by gilbarbara** [comment]
Hey @crow1796 
This is by design since this library doesn't interact with the host app's elements in any way, so it can't know when an element changed sizes. Adding listeners to these elements could have nasty side-effects...

I think is better for users to stop the tour when the user interacts with an element and restart it afterward if necessary.
