### ISSUE TITLE
Option to remove top right "X" exit button

### ISSUE THREAD

**Issue by rebeccalambert** [gilbarbara/react-joyride#606]
## 🚀 Feature Idea

Have a prop that removed / hides / disables the exit button in the top right of the tooltip walkthrough.

## Motivation

I want to make it mandatory for users to go through the entire walkthrough, without being able to close it at any point.

**Comment by gilbarbara** [comment]
hey @rebeccalambert 

You can use a custom tooltip or the controlled mode if you need to customize the whole experience.
Check the [demo](https://github.com/gilbarbara/react-joyride-demo) for examples.

**Comment by gilbarbara** [comment]
You can also customize the [styles](https://docs.react-joyride.com/styling)

**Comment by Pareder** [comment]
@gilbarbara I have found new workaround for this issue: adding `hideCloseButton: true` to each step will hide this close button, because in code you have [such condition](https://github.com/gilbarbara/react-joyride/blob/master/src/components/Tooltip/Container.js#L82). But in documentation for step (https://docs.react-joyride.com/step) you don't have such prop, is it deprecated or what?

Also it would be good to have such possibility without passing this prop to each step. You have `floaterProps` prop and `react-floater` has prop `showCloseButton`, but currently you are not using it. Maybe you can use it or just complete the documentation for step?

**Comment by gilbarbara** [comment]
@Pareder Added to the docs in c33746d542fd8203d2e85ed07a0c07753c3cc86f
